import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import rollupJson from "rollup-plugin-json";
import commonjs from "@rollup/plugin-commonjs";
import execute from "rollup-plugin-execute";
import svelte from "rollup-plugin-svelte";
import autoPreprocess from 'svelte-preprocess';
import path from "path";
import babel from "@rollup/plugin-babel";

const isProd = process.env.BUILD === "production";

const currentDir = path.dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository 
> https://github.com/bagaking/obsidian-plugin-scaffold
*/
`;

// const TEST_VAULT =

export default {
  input: "src/main.ts",
  output: {
    dir: "./build",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    execute([
      `mkdir -p ${currentDir}/build`,
      `cp -u ${currentDir}/manifest.json ${currentDir}/build/manifest.json`,
      `cp -u ${currentDir}/styles.css ${currentDir}/build/styles.css`,
    ]),
    babel({
      presets: ['@babel/preset-react'],
      babelHelpers: 'bundled'
    }),
    typescript(),
    nodeResolve({ browser: true }),
    rollupJson(),
    commonjs(),
    svelte({
      preprocess: autoPreprocess()
    })
  ],
  onwarn(warning, warn) {
    // workaround to prevent rollup build error
    if (
      warning.code === "EVAL" &&
      /.*\/node_modules\/file-type\/.*/.test(warning.loc.file)
    ) {
      return;
    }
    warn(warning);
  },
};
