import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import copy from "./bagaking.copy.mjs"

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
> https://github.com/bagaking/obsidian-plugin-scaffold
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: "build",
	plugins: [
		copy({from: "./manifest.json", dest: "./build/manifest.json"}),
		copy({from: "./versions.json", dest: "./build/versions.json"}),
		copy({from: "./statics", dest: "./build/statics"}),

	],
}).catch(() => process.exit(1));
